FROM node:18

WORKDIR /usr/src/app

# Copy everything from our directory into the work directory
COPY . .

RUN chmod +x /usr/src/app/run_and_deploy.sh
RUN apt-get update
RUN apt-get install bash -y
RUN apt-get install python3 -y && apt-get install python3-pip -y
RUN pip3 install PyYAML --break-system-packages
RUN npm install -g pnpm
RUN pnpm build
RUN mkdir ./build/public
RUN touch ./build/public/doc.html

EXPOSE 3000

CMD [ "sh", "run_and_deploy.sh"]