version: '3.8'

services:
  dashboard:
    platform: linux/x86_64
    image: ghcr.io/autowinto/bsc2024-dashboard:latest
    container_name: bsc2024-dashboard
    ports:
      - "8080:8080"

  backend:
    platform: linux/x86_64
    image: ghcr.io/autowinto/bsc2024-backend:latest
    container_name: bsc2024-backend
    ports:
      - "3000:3000"
    environment:
      - DEV_ENV=${DEV_ENV}
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: postgres:13
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
