info:
  title: Untitled-converter's API
  version: 1.0.0
  description: Documentation of the API routes for the "Untitled-converter" application.
swagger: "2.0"
paths: {}
definitions: {}
responses: {}
parameters: {}
securityDefinitions: {}
tags: []
